global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node-execution"
    static_configs:
      - targets:
          - "execution:6060"

  - job_name: "node-consensus"
    static_configs:
      - targets:
          - "node:7300"
